<?php

namespace PointWeb\GuestbookBundle\Entity;

use PointWeb\AppBundle\Entity\PagerRepository;

/**
 * GuestbookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GuestbookRepository extends PagerRepository
{
}
