point_web_guest_book_admin:
    resource: "@PointWebGuestbookBundle/Resources/config/routing/admin_guestbook.yml"
    prefix:   /admin/guestbook


point_web_guest_book:
    resource: "@PointWebGuestbookBundle/Resources/config/routing/guestbook.yml"
    prefix:   /guestbook