admin_product:
    path:     /
    defaults: { _controller: "PointWebProductBundle:Product:index" }

admin_product_show:
    path:     /{id}/show
    defaults: { _controller: "PointWebProductBundle:Product:show" }

admin_product_new:
    path:     /new
    defaults: { _controller: "PointWebProductBundle:Product:new" }

admin_product_create:
    path:     /create
    defaults: { _controller: "PointWebProductBundle:Product:create" }
    methods:  POST

admin_product_edit:
    path:     /{id}/edit
    defaults: { _controller: "PointWebProductBundle:Product:edit" }

admin_product_update:
    path:     /{id}/update
    defaults: { _controller: "PointWebProductBundle:Product:update" }
    methods:  [POST, PUT]

admin_product_delete:
    path:     /{id}/delete
    defaults: { _controller: "PointWebProductBundle:Product:delete" }
    methods:  [POST, DELETE]

admin_product_subcat:
    path:     /{id}/sub
    defaults: { _controller: "PointWebProductBundle:Product:sub" }

admin_product_sort:
    path:     /{id}/sort
    defaults: { _controller: "PointWebProductBundle:Product:sort" }
