<?php

namespace PointWeb\FaqBundle\Entity;

use PointWeb\AdminBundle\Entity\PagerRepository;

/**
 * FaqRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FaqRepository extends PagerRepository
{
}
