<?php

namespace Proxies\__CG__\PointWeb\ProductBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Product extends \PointWeb\ProductBundle\Entity\Product implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = ['pictures' => NULL];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {
        unset($this->pictures);

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }

    /**
     * 
     * @param string $name
     */
    public function __get($name)
    {
        if (array_key_exists($name, $this->__getLazyProperties())) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__get', [$name]);

            return $this->$name;
        }

        trigger_error(sprintf('Undefined property: %s::$%s', __CLASS__, $name), E_USER_NOTICE);
    }

    /**
     * 
     * @param string $name
     * @param mixed  $value
     */
    public function __set($name, $value)
    {
        if (array_key_exists($name, $this->__getLazyProperties())) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__set', [$name, $value]);

            $this->$name = $value;

            return;
        }

        $this->$name = $value;
    }

    /**
     * 
     * @param  string $name
     * @return boolean
     */
    public function __isset($name)
    {
        if (array_key_exists($name, $this->__getLazyProperties())) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__isset', [$name]);

            return isset($this->$name);
        }

        return false;
    }

    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'PointWeb\\ProductBundle\\Entity\\Product' . "\0" . 'id', '' . "\0" . 'PointWeb\\ProductBundle\\Entity\\Product' . "\0" . 'title', '' . "\0" . 'PointWeb\\ProductBundle\\Entity\\Product' . "\0" . 'reference', '' . "\0" . 'PointWeb\\ProductBundle\\Entity\\Product' . "\0" . 'resum', '' . "\0" . 'PointWeb\\ProductBundle\\Entity\\Product' . "\0" . 'description', '' . "\0" . 'PointWeb\\ProductBundle\\Entity\\Product' . "\0" . 'price', '' . "\0" . 'PointWeb\\ProductBundle\\Entity\\Product' . "\0" . 'promotionPrice', '' . "\0" . 'PointWeb\\ProductBundle\\Entity\\Product' . "\0" . 'urlLink', '' . "\0" . 'PointWeb\\ProductBundle\\Entity\\Product' . "\0" . 'position', '' . "\0" . 'PointWeb\\ProductBundle\\Entity\\Product' . "\0" . 'online', '' . "\0" . 'PointWeb\\ProductBundle\\Entity\\Product' . "\0" . 'layout', '' . "\0" . 'PointWeb\\ProductBundle\\Entity\\Product' . "\0" . 'promotionStartDate', '' . "\0" . 'PointWeb\\ProductBundle\\Entity\\Product' . "\0" . 'promotionEndDate', 'pictures', '' . "\0" . 'PointWeb\\ProductBundle\\Entity\\Product' . "\0" . 'updateDate', '' . "\0" . 'PointWeb\\ProductBundle\\Entity\\Product' . "\0" . 'createDate', '' . "\0" . 'PointWeb\\ProductBundle\\Entity\\Product' . "\0" . 'product_category'];
        }

        return ['__isInitialized__', '' . "\0" . 'PointWeb\\ProductBundle\\Entity\\Product' . "\0" . 'id', '' . "\0" . 'PointWeb\\ProductBundle\\Entity\\Product' . "\0" . 'title', '' . "\0" . 'PointWeb\\ProductBundle\\Entity\\Product' . "\0" . 'reference', '' . "\0" . 'PointWeb\\ProductBundle\\Entity\\Product' . "\0" . 'resum', '' . "\0" . 'PointWeb\\ProductBundle\\Entity\\Product' . "\0" . 'description', '' . "\0" . 'PointWeb\\ProductBundle\\Entity\\Product' . "\0" . 'price', '' . "\0" . 'PointWeb\\ProductBundle\\Entity\\Product' . "\0" . 'promotionPrice', '' . "\0" . 'PointWeb\\ProductBundle\\Entity\\Product' . "\0" . 'urlLink', '' . "\0" . 'PointWeb\\ProductBundle\\Entity\\Product' . "\0" . 'position', '' . "\0" . 'PointWeb\\ProductBundle\\Entity\\Product' . "\0" . 'online', '' . "\0" . 'PointWeb\\ProductBundle\\Entity\\Product' . "\0" . 'layout', '' . "\0" . 'PointWeb\\ProductBundle\\Entity\\Product' . "\0" . 'promotionStartDate', '' . "\0" . 'PointWeb\\ProductBundle\\Entity\\Product' . "\0" . 'promotionEndDate', '' . "\0" . 'PointWeb\\ProductBundle\\Entity\\Product' . "\0" . 'updateDate', '' . "\0" . 'PointWeb\\ProductBundle\\Entity\\Product' . "\0" . 'createDate', '' . "\0" . 'PointWeb\\ProductBundle\\Entity\\Product' . "\0" . 'product_category'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Product $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

            unset($this->pictures);
        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle($title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', [$title]);

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', []);

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setPromotionPrice($promotionPrice)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPromotionPrice', [$promotionPrice]);

        return parent::setPromotionPrice($promotionPrice);
    }

    /**
     * {@inheritDoc}
     */
    public function getPromotionPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPromotionPrice', []);

        return parent::getPromotionPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrice($price)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrice', [$price]);

        return parent::setPrice($price);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice', []);

        return parent::getPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setReference($reference)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReference', [$reference]);

        return parent::setReference($reference);
    }

    /**
     * {@inheritDoc}
     */
    public function getReference()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReference', []);

        return parent::getReference();
    }

    /**
     * {@inheritDoc}
     */
    public function getResum()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResum', []);

        return parent::getResum();
    }

    /**
     * {@inheritDoc}
     */
    public function setResum($resum)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResum', [$resum]);

        return parent::setResum($resum);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function setUrlLink($urlLink)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUrlLink', [$urlLink]);

        return parent::setUrlLink($urlLink);
    }

    /**
     * {@inheritDoc}
     */
    public function getUrlLink()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUrlLink', []);

        return parent::getUrlLink();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductCategory(\PointWeb\ProductBundle\Entity\ProductCategory $product_category = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductCategory', [$product_category]);

        return parent::setProductCategory($product_category);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductCategory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductCategory', []);

        return parent::getProductCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function setPosition($position)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPosition', [$position]);

        return parent::setPosition($position);
    }

    /**
     * {@inheritDoc}
     */
    public function getPosition()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPosition', []);

        return parent::getPosition();
    }

    /**
     * {@inheritDoc}
     */
    public function setLayout($layout)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLayout', [$layout]);

        return parent::setLayout($layout);
    }

    /**
     * {@inheritDoc}
     */
    public function getLayout()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLayout', []);

        return parent::getLayout();
    }

    /**
     * {@inheritDoc}
     */
    public function setOnline($online)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOnline', [$online]);

        return parent::setOnline($online);
    }

    /**
     * {@inheritDoc}
     */
    public function getOnline()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOnline', []);

        return parent::getOnline();
    }

    /**
     * {@inheritDoc}
     */
    public function setPromotionStartDate($promotionStartDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPromotionStartDate', [$promotionStartDate]);

        return parent::setPromotionStartDate($promotionStartDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getPromotionStartDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPromotionStartDate', []);

        return parent::getPromotionStartDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setPromotionEndDate($promotionEndDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPromotionEndDate', [$promotionEndDate]);

        return parent::setPromotionEndDate($promotionEndDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getPromotionEndDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPromotionEndDate', []);

        return parent::getPromotionEndDate();
    }

    /**
     * {@inheritDoc}
     */
    public function addPicture(\PointWeb\AdminBundle\Entity\File $picture)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPicture', [$picture]);

        return parent::addPicture($picture);
    }

    /**
     * {@inheritDoc}
     */
    public function removePicture(\PointWeb\AdminBundle\Entity\File $picture)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePicture', [$picture]);

        return parent::removePicture($picture);
    }

    /**
     * {@inheritDoc}
     */
    public function getPictures()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPictures', []);

        return parent::getPictures();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdateDate($updateDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdateDate', [$updateDate]);

        return parent::setUpdateDate($updateDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdateDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdateDate', []);

        return parent::getUpdateDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreateDate($createDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreateDate', [$createDate]);

        return parent::setCreateDate($createDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreateDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreateDate', []);

        return parent::getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    public function preUpdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'preUpdate', []);

        return parent::preUpdate();
    }

}
