<?php

namespace PointWeb\GalleryBundle\Entity;
use PointWeb\AdminBundle\Entity\PagerRepository;

/**
 * GalleryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GalleryRepository extends PagerRepository
{
}
