<?php

namespace PointWeb\MapBundle\Entity;

use PointWeb\AdminBundle\Entity\PagerRepository;

/**
 * mapRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class mapRepository extends PagerRepository
{
}
