point_web_product:
    resource: "@PointWebProductBundle/Resources/config/routing.yml"
    prefix:   /

point_web_ged:
    resource: "@PointWebGedBundle/Resources/config/routing.yml"
    prefix:   /

point_web_faq:
    resource: "@PointWebFaqBundle/Resources/config/routing.yml"
    prefix:   /

point_web_gallery:
    resource: "@PointWebGalleryBundle/Resources/config/routing.yml"
    prefix:   /

point_web_guest_book:
    resource: "@PointWebGuestbookBundle/Resources/config/routing.yml"
    prefix:   /

point_web_partner:
    resource: "@PointWebPartnerBundle/Resources/config/routing.yml"
    prefix:   /

point_web_news:
    resource: "@PointWebNewsBundle/Resources/config/routing.yml"
    prefix:   /

point_web_page:
    resource: "@PointWebPageBundle/Resources/config/routing.yml"
    prefix:   /

point_web_map:
    resource: "@PointWebMapBundle/Resources/config/routing.yml"
    prefix:   /

point_web_user:
    resource: "@PointWebUserBundle/Resources/config/routing.yml"
    prefix:   /

point_web_admin:
    resource: "@PointWebAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

point_web_app:
    resource: "@PointWebAppBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"