point_web_app_homepage:
    path:     /
    defaults: { _controller: PointWebAppBundle:Default:index }

point_web_app_legal:
    path:     /legal
    defaults: { _controller: PointWebAppBundle:Default:legal }

point_web_app_sitemap:
    path:     /sitemap
    defaults: { _controller: PointWebAppBundle:Default:sitemap }

point_web_app_contact:
    path:     /contact
    defaults: { _controller: PointWebAppBundle:Default:contact }

point_web_app_thanks:
    path:     /thanks
    defaults: { _controller: PointWebAppBundle:Default:thanks }

point_web_contact_admin:
    resource: "@PointWebAppBundle/Resources/config/routing/admin_contact.yml"
    prefix:   /admin/contact

