<?php

namespace PointWeb\AppBundle\Entity;


use PointWeb\AdminBundle\Entity\PagerRepository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends PagerRepository
{
}
