<?php

namespace PointWeb\PartnerBundle\Entity;
use PointWeb\AdminBundle\Entity\PagerRepository;


/**
 * PartnerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartnerRepository extends PagerRepository
{

    public function getPartner($category)
    {
        $query = $this->createQueryBuilder('a')
            ->add('select', 'a')
            // Jointure sur l'attribut categories
            ->leftJoin('a.partner_category', 'c')

            ->where('c.id = :cat')
            ->setParameter('cat',$category)
        ;

        $query = $query->getQuery()->getResult();
        //var_dump($query);//die;
        return $query;

    }

}
