<?php

namespace PointWeb\PartnerBundle\Entity;

use PointWeb\AdminBundle\Entity\PagerRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartnerCategoryRepository extends PagerRepository
{

}
