<?php

namespace PointWeb\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * PagerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PagerRepository extends EntityRepository
{
    public function pager($orderBy = 'id', $page = 1, $maxPerPage = 10)
    {
        $q = $this->createQueryBuilder('a');
        $q->addOrderBy('a.' . $orderBy, 'ASC');
        $q->setFirstResult(($page - 1) * $maxPerPage)
            ->setMaxResults($maxPerPage);
        return new Paginator($q);
    }

    public function count()
    {
        return $this->createQueryBuilder('a')
            ->select('COUNT(a)')
            ->getQuery()
            ->getSingleScalarResult();
    }
}
