<?php

namespace PointWeb\PageBundle\Entity;
use PointWeb\AdminBundle\Entity\PagerRepository;


/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class PageRepository extends PagerRepository
{
}
